SIM ?= verilator
FST ?= -fst
TOPLEVEL_LANG ?= verilog

SRC_DIR = $(PWD)/../src
PROJECT_SOURCES = dcache_ahb_ctrl.sv project.v

TEST ?= uvm.tb.b2b.cpu.tests.cl_cpu_b2b_simple_test

TOPLEVEL = cpu_b2b_tb
SIM_BUILD = sim_build/cpu_b2b
VERILOG_SOURCES += $(addprefix $(SRC_DIR)/,$(PROJECT_SOURCES))
VERILOG_SOURCES += $(PWD)/cpu_b2b_tb.sv

COMPILE_ARGS += -I$(SRC_DIR)

MODULE = $(TEST)

include $(shell cocotb-config --makefiles)/Makefile.sim
